package mc.shiracraft.core.gui.tab;

import mc.shiracraft.core.Core;
import mc.shiracraft.core.gui.screen.UnlockOverviewScreen;
import mc.shiracraft.core.registry.ItemRegistry;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.inventory.InventoryScreen;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.client.event.ScreenEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;

import java.util.HashMap;
import java.util.Map;

/**
 * Represents a custom tab that can be added to the inventory screen.
 * This tab displays a slot coin icon and logs when clicked.
 * Handles its own rendering and click events.
 *
 * Generated by Claude Sonnet 4.5 as an example. Needs to manually changed to match the mod's style.
 */
@Mod.EventBusSubscriber(modid = Core.MOD_ID, value = Dist.CLIENT)
public class InventoryTab {
    // Cache tabs per inventory screen instance
    private static final Map<InventoryScreen, InventoryTab> tabCache = new HashMap<>();
    // Tab dimensions and position
    private static final int TAB_WIDTH = 28;
    private static final int TAB_HEIGHT = 32;
    private static final int TAB_OFFSET_X = 176;
    private static final int TAB_OFFSET_Y = 4;
    private static final int ITEM_OFFSET_X = 6;
    private static final int ITEM_OFFSET_Y = 8;

    // Tab colors
    private static final int BACKGROUND_COLOR = 0xFF8B8B8B;
    private static final int BACKGROUND_COLOR_SELECTED = 0xFFC6C6C6;
    private static final int BORDER_COLOR = 0xFF373737;
    private static final int HIGHLIGHT_COLOR = 0xFFFFFFFF;

    private final InventoryScreen inventoryScreen;
    private boolean selected;

    private InventoryTab(InventoryScreen inventoryScreen) {
        this.inventoryScreen = inventoryScreen;
        this.selected = false;
    }

    /**
     * Event handler for rendering the tab on inventory screens.
     */
    @SubscribeEvent
    public static void onScreenRender(ScreenEvent.Render.Post event) {
        if (event.getScreen() instanceof InventoryScreen inventoryScreen) {
            InventoryTab tab = tabCache.computeIfAbsent(inventoryScreen, InventoryTab::new);
            tab.render(event.getGuiGraphics());
        }
    }

    /**
     * Event handler for handling clicks on the tab.
     */
    @SubscribeEvent
    public static void onScreenMouseClicked(ScreenEvent.MouseButtonPressed.Pre event) {
        var screen = event.getScreen();
        if (screen instanceof InventoryScreen inventoryScreen) {
            InventoryTab tab = tabCache.computeIfAbsent(inventoryScreen, InventoryTab::new);

            if (tab.handleClick(event.getMouseX(), event.getMouseY())) {
                var minecraft = screen.getMinecraft();
                minecraft.setScreen(new UnlockOverviewScreen(minecraft.player));
                event.setCanceled(true);
            }
        }
    }

    /**
     * Event handler for cleaning up cached tabs when screens are closed.
     */
    @SubscribeEvent
    public static void onScreenClosed(ScreenEvent.Closing event) {
        if (event.getScreen() instanceof InventoryScreen inventoryScreen) {
            tabCache.remove(inventoryScreen);
        }
    }

    /**
     * Renders the tab on the inventory screen.
     */
    private void render(GuiGraphics guiGraphics) {
        int leftPos = (inventoryScreen.width - 176) / 2;
        int topPos = (inventoryScreen.height - 166) / 2;

        int tabX = leftPos + TAB_OFFSET_X;
        int tabY = topPos + TAB_OFFSET_Y;

        // Render tab background
        renderTabBackground(guiGraphics, tabX, tabY);

        // Render slot coin item on the tab
        ItemStack slotCoin = new ItemStack(ItemRegistry.SLOT_COIN.get());
        guiGraphics.renderItem(slotCoin, tabX + ITEM_OFFSET_X, tabY + ITEM_OFFSET_Y);
    }

    /**
     * Handles mouse click events on the tab.
     * Returns true if the click was within the tab bounds.
     */
    private boolean handleClick(double mouseX, double mouseY) {
        int leftPos = (inventoryScreen.width - 176) / 2;
        int topPos = (inventoryScreen.height - 166) / 2;

        int tabX = leftPos + TAB_OFFSET_X;
        int tabY = topPos + TAB_OFFSET_Y;

        // Check if click is within tab bounds
        if (mouseX >= tabX && mouseX <= tabX + TAB_WIDTH &&
            mouseY >= tabY && mouseY <= tabY + TAB_HEIGHT) {

            // Log to console when tab is clicked
            Core.LOGGER.info("Unlock Overview tab clicked!");
            return true;
        }

        return false;
    }

    /**
     * Renders the tab background with a 3D appearance.
     */
    private void renderTabBackground(GuiGraphics guiGraphics, int x, int y) {
        int backgroundColor = selected ? BACKGROUND_COLOR_SELECTED : BACKGROUND_COLOR;

        // Main tab body
        guiGraphics.fill(x, y, x + TAB_WIDTH, y + TAB_HEIGHT, backgroundColor);

        // Border
        guiGraphics.fill(x, y, x + 1, y + TAB_HEIGHT, BORDER_COLOR); // Left edge
        guiGraphics.fill(x, y, x + TAB_WIDTH, y + 1, BORDER_COLOR); // Top edge
        guiGraphics.fill(x, y + TAB_HEIGHT - 1, x + TAB_WIDTH, y + TAB_HEIGHT, BORDER_COLOR); // Bottom edge
        guiGraphics.fill(x + TAB_WIDTH - 1, y, x + TAB_WIDTH, y + TAB_HEIGHT, BORDER_COLOR); // Right edge

        // Highlight on top and left for 3D effect
        guiGraphics.fill(x + 1, y + 1, x + TAB_WIDTH - 1, y + 2, HIGHLIGHT_COLOR);
        guiGraphics.fill(x + 1, y + 1, x + 2, y + TAB_HEIGHT - 1, HIGHLIGHT_COLOR);
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }
}

